In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
# One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[3861, 4061, 37, 2907],
 [3861, 4061, 37, 9418],
 [3861, 579, 37, 8715],
 [4379, 694, 2818, 6880, 2959],
 [4379, 694, 2818, 6880, 4702],
 [7921, 3861, 796, 37, 6862],
 [2505, 7256, 5298, 6880]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [15]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)  # by this, doing the same size of every sentence
embedded_docs

array([[   0,    0,    0,    0, 3861, 4061,   37, 2907],
       [   0,    0,    0,    0, 3861, 4061,   37, 9418],
       [   0,    0,    0,    0, 3861,  579,   37, 8715],
       [   0,    0,    0, 4379,  694, 2818, 6880, 2959],
       [   0,    0,    0, 4379,  694, 2818, 6880, 4702],
       [   0,    0,    0, 7921, 3861,  796,   37, 6862],
       [   0,    0,    0,    0, 2505, 7256, 5298, 6880]])

In [11]:
# feature representation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile("adam", "mse")

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 50ms/step


array([[[ 0.03344946, -0.01554183,  0.04336059, -0.01422261,
         -0.02529941,  0.02529052,  0.00412335,  0.04221246,
         -0.01001807,  0.04532367],
        [ 0.03344946, -0.01554183,  0.04336059, -0.01422261,
         -0.02529941,  0.02529052,  0.00412335,  0.04221246,
         -0.01001807,  0.04532367],
        [ 0.03344946, -0.01554183,  0.04336059, -0.01422261,
         -0.02529941,  0.02529052,  0.00412335,  0.04221246,
         -0.01001807,  0.04532367],
        [ 0.03344946, -0.01554183,  0.04336059, -0.01422261,
         -0.02529941,  0.02529052,  0.00412335,  0.04221246,
         -0.01001807,  0.04532367],
        [ 0.0218041 , -0.02384733, -0.01269579,  0.04028106,
          0.03842849,  0.01849503, -0.01929764, -0.0068063 ,
          0.02551529,  0.04063095],
        [ 0.03668937, -0.02897332,  0.03581548, -0.0117659 ,
          0.01581985,  0.00802556, -0.04926115, -0.01554245,
         -0.01422011, -0.04858202],
        [-0.02123772,  0.04366637, -0.02972207, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3861, 4061,   37, 2907])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 112ms/step


array([[ 0.03344946, -0.01554183,  0.04336059, -0.01422261, -0.02529941,
         0.02529052,  0.00412335,  0.04221246, -0.01001807,  0.04532367],
       [ 0.03344946, -0.01554183,  0.04336059, -0.01422261, -0.02529941,
         0.02529052,  0.00412335,  0.04221246, -0.01001807,  0.04532367],
       [ 0.03344946, -0.01554183,  0.04336059, -0.01422261, -0.02529941,
         0.02529052,  0.00412335,  0.04221246, -0.01001807,  0.04532367],
       [ 0.03344946, -0.01554183,  0.04336059, -0.01422261, -0.02529941,
         0.02529052,  0.00412335,  0.04221246, -0.01001807,  0.04532367],
       [ 0.0218041 , -0.02384733, -0.01269579,  0.04028106,  0.03842849,
         0.01849503, -0.01929764, -0.0068063 ,  0.02551529,  0.04063095],
       [ 0.03668937, -0.02897332,  0.03581548, -0.0117659 ,  0.01581985,
         0.00802556, -0.04926115, -0.01554245, -0.01422011, -0.04858202],
       [-0.02123772,  0.04366637, -0.02972207, -0.01826196,  0.03714582,
         0.01471842, -0.02456207, -0.04163285